# Generated by Django 6.0.4 on 2026-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0003_group_icon_groupmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalexpense',
            name='account',
            field=models.CharField(default='Bank Account', max_length=100),
        ),
    ]
