# Generated by Django 6.0.4 on 2026-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0004_personalexpense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='account',
            field=models.CharField(default='Bank Account', max_length=100),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=100),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='account',
            field=models.CharField(default='Bank Account', max_length=100),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', max_length=100),
        ),
    ]
