# Generated by Django 6.0.4 on 2026-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0006_alter_group_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
